DROP TABLE users PURGE;

CREATE TABLE users (
    emailid        VARCHAR2(50) PRIMARY KEY,
    password       VARCHAR2(30) NOT NULL,
    username       VARCHAR2(20) NOT NULL UNIQUE,
    phonenumber    VARCHAR2(20) NOT NULL,
    gender         VARCHAR2(10),
    dateofbirth    DATE,
    lastloggedin   DATE,
    imageurl       VARCHAR2(50),
    image          BFILE,
    proversion     CHAR(1)
);

INSERT INTO users VALUES (
    'ankur.patel@humber.ca',
    'Ankur@123',
    'Dark_Knight',
    '+1-612-7788',
    'Male',
    '20-Dec-1994',
    '19-Jan-2019',
    'abc',
    bfilename('GIF_FILES', 'Ankur.JPG'),
    'Y'
);

SELECT
    *
FROM
    users;

COMMIT;

DROP TABLE questions PURGE;

CREATE TABLE questions (
    questionno   NUMBER(2),
    question     VARCHAR2(255),
    option1      VARCHAR2(255),
    option2      VARCHAR2(255),
    option3      VARCHAR2(255),
    option4      VARCHAR2(255),
    correctans   NUMBER(2),
    points       NUMBER,
    categoryno   NUMBER NOT NULL REFERENCES category ( categoryno )
);

DROP TABLE category;

CREATE TABLE category (
    categoryno        NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
    PRIMARY KEY,
    categoryname      VARCHAR2(20),
    categorydetails   VARCHAR2(20)
);

DROP TABLE quizresult PURGE;

CREATE TABLE quizresult (
    quizno            NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
    PRIMARY KEY,
    scoreobtained     NUMBER,
    percentagescore   NUMBER,
    timeused          NUMBER,
    username          VARCHAR2(20) NOT NULL
        REFERENCES users ( username )
);